---
version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: resume-app:latest
    ports:
      - "80:80"
    expose:
      - 80
    restart: always
    environment:
      PORT: 80
      ADDRESS: 0.0.0.0
    