steps:
  - label: "Build docker image"
    command: sudo docker build -t neiljoaquin/resume-app:latest .
  - label: "Push to prod"
    if: build.branch == "main"
    commands: 
      - sudo docker login -u neiljoaquin -p dckr_pat_519Q3oi7GugN8EM07IvHWLbSb2M
      - docker push neiljoaquin/resume-app:1