steps:
  - label: "Build docker image"
    key: "build"
    command: sudo docker build -t neiljoaquin/resume-app:1 .
  
  - label: "Push to prod"
    key: "push_to_prod"
    depends_on: "build"
    if: build.branch == "main"
    commands: 
      - sudo docker login -u neiljoaquin -p dckr_pat_519Q3oi7GugN8EM07IvHWLbSb2M
      - sudo docker push neiljoaquin/resume-app:1